anuncio/urls.py
from django.urls import path
from anuncio.views import ListarAnuncios, CriarAnuncios, DeletarAnuncio, EditarAnuncios

urlpatterns = [
    path('', ListarAnuncios.as_view(), name='listar-anuncios'),
    path('novo/', CriarAnuncios.as_view(), name='criar-anuncio'),
    path('<int:pk>/', EditarAnuncios.as_view(), name='editar-anuncio'),
    path('deletar/<int:pk>/', DeletarAnuncio.as_view(), name='deletar-anuncio')
]

sistema/urls.py
from django.contrib import admin
from django.urls import include, path
from sistema.views import Login, Logout, LoginAPI
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    #path('autenticacao-api/', obtain_auth_token),
    path('autenticacao-api/', LoginAPI.as_view()),
    path('logout/', Logout.as_view(), name='logout'),
    path('veiculo/', include('veiculo.urls'), name='veiculo'),
    path('anuncio/', include('anuncio.urls'), name='anuncio')
]

veiculo/urls.py
from django.urls import path
from veiculo.views import FotoVeiculo, ListarVeiculos, CriarVeiculos, EditarVeiculos, DeletarVeiculo, APIListarCriarVeiculos, APIObterEditarDeletarVeiculos

urlpatterns = [
  path('', ListarVeiculos.as_view(), name='listar-veiculos'),
  path('novo/', CriarVeiculos.as_view(), name='criar-veiculo'),
  path('fotos/<str:arquivo>/', FotoVeiculo.as_view(), name='foto-veiculo'),
  path('<int:pk>/', EditarVeiculos.as_view(), name='editar-veiculo'),
  path('deletar/<int:pk>/', DeletarVeiculo.as_view(), name='deletar-veiculo'),
  path('api/', APIListarCriarVeiculos.as_view(), name='api-listar-criar-veiculos'),
  path('api/<int:pk>/', APIObterEditarDeletarVeiculos.as_view(), name='api-obter-editar-deletar-veiculos')
]

veiculo/models.py
from django.db import models
from datetime import datetime
from veiculo.consts import OPCOES_MARCAS, OPCOES_CORES, OPCOES_COMBUSTIVEIS


# Create your models here.
class Veiculo(models.Model):
    marca = models.PositiveSmallIntegerField(choices=OPCOES_MARCAS)
    modelo = models.CharField(max_length=100)
    ano = models.IntegerField()
    cor = models.SmallIntegerField(choices=OPCOES_CORES)
    foto = models.ImageField(blank=True, null=True, upload_to='veiculo/fotos')
    combustivel = models.SmallIntegerField(choices=OPCOES_COMBUSTIVEIS)

    @property # Se comporta como um atributo mas nao fica na base de dados
    def veiculo_novo(self):
        return self.ano == datetime.now().year
    
    def __str__(self):
        return '{0} - {1} ({2}/{3})'.format(
            self.marca,
            self.modelo,
            self.ano,
            self.get_cor_display()
        )
    

    def ano_de_uso(self):
        return datetime.now().year - self.ano

veiculo/forms.py
from django import forms
from veiculo.models import Veiculo


class FormularioVeiculo(forms.ModelForm):
    class Meta():
        model = Veiculo
        exclude = []

veiculo/views.py
from django.http import FileResponse, Http404
from django.urls import reverse_lazy
from sistema.bibliotecas import LoginObrigatorio
from veiculo.models import Veiculo
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from veiculo.forms import FormularioVeiculo
from veiculo.serializers import SerializadorVeiculo
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework import permissions



class ListarVeiculos(LoginObrigatorio, ListView):

    """
    View para listar veiculos cadastrados.
    """

    model = Veiculo
    context_object_name = 'veiculos'
    template_name = 'veiculo/listar.html'

    def get_queryset(self, **kwargs):
        pesquisa = self.request.GET.get('pesquisa', None)
        queryset = Veiculo.objects.all()
        if pesquisa is not None:
          queryset = queryset.filter(modelo__icontains=pesquisa)  
        return queryset
    
class FotoVeiculo(LoginObrigatorio):

    """
    View para retornar a foto dos veiculos.
    """

    def get(self, request, arquivo):
        try:
            veiculo = Veiculo.objects.get(foto='veiculo/fotos/{}'.format(arquivo))
            return FileResponse(veiculo.foto)
        
        except ObjectDoesNotExist:
            raise Http404("Foto não encontrada ou acesso não autorizado!")
        
        except Exception as exception:
            raise exception
        
class CriarVeiculos(LoginObrigatorio, CreateView):

    """
    View para a criação de novos veiculos.
    """

    model = Veiculo
    form_class = FormularioVeiculo
    template_name = 'veiculo/novo.html'
    success_url = reverse_lazy('listar-veiculos')

class EditarVeiculos(LoginObrigatorio, UpdateView):

    """
    View para editar veiculos ja cadastrados.
    """
    
    model = Veiculo
    form_class = FormularioVeiculo
    template_name = 'veiculo/editar.html'
    success_url = reverse_lazy('listar-veiculos')

class DeletarVeiculo(LoginObrigatorio, DeleteView):

    """
    View para deletar veiculos.
    """

    model = Veiculo
    template_name = 'veiculo/deletar.html'
    success_url = reverse_lazy('listar-veiculos')

class APIListarCriarVeiculos(ListCreateAPIView):

    serializer_class = SerializadorVeiculo
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Veiculo.objects.all()

class APIObterEditarDeletarVeiculos(RetrieveUpdateDestroyAPIView):
    
    serializer_class = SerializadorVeiculo
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Veiculo.objects.all()

templates/veiculo/deletar.html
{% extends "../base.html" %}

{% block titulo %} Deletar veiculo {{object.modelo}} {% endblock %}

{% block conteudo %}

<form action="/veiculo/deletar/{{object.pk}}/" method="post">
    {% csrf_token %}

    <center>
        <div class="alert alert-danger" role="alert">
            <p> Tem certeza que deseja excluir o veiculo "{{object}}" ?</p>
        </div>
        <input type="submit" value="Confirmar" class="btn btn-danger" />
    </center>
</form>

{% endblock %}

templates/veiculo/editar.html
{% extends "../base.html" %}

{% block titulo %} Edição do veículo {{ object.modelo }} {% endblock %}

{% block conteudo %}

<form action="/veiculo/{{ object.pk }}/" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="col-6">
      <label for="marca" class="form-label">Marca</label>
      {{ form.marca }}
    </div>
    <div class="col-6">
    <label for="modelo" class="form-label">Modelo</label>
      {{ form.modelo }}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label for="ano" class="form-label">Ano</label>
      {{ form.ano }}
    </div>
    <div class="col-6">
      <label for="cor" class="form-label">Cor</label>
      {{ form.cor }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <label for="combustivel" class="form-label">Combustível</label>
      {{ form.combustivel }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <label for="foto" class="form-label">Foto</label>
      {{ form.foto }}
    </div>
  </div>
  <input type="submit" value="Salvar" class="btn btn-primary mt-3 float-end" />
</form>

{% endblock %}

templates/veiculo/listar.html
{% extends "../base.html" %}

{% block titulo %} Listagem de veículos {% endblock %}

{% block conteudo %}
<div class="container-fluid pb-3">
    <div class="d-grid border-top border-info border-2">

      <form action="/veiculo/" method="GET">
        <div class="row">
          <div class="col-2 offset-10 mt-3">
            <div class="input-group mb-3">
              <input type="text" name="pesquisa" class="form-control" value="{{ pesquisa }}">
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">pesquisar</button>
              </div>
            </div>
          </div>
        </div>
      </form>

      <center>
        <div class="bg-body-tertiary border rounded-3 justify-content-center">
          {% for v in veiculos %}
          <div class="card card-veiculo mt-3 mb-3">

            {% if v.foto %}
              <img src="{{v.foto.url}}" class="card-img-top" />
            {% else %}
              Veículo sem foto
            {% endif %}

            <div class="card-body">
              <h5 class="card-title">{{v.get_marca_display}}</h5>
              <p class="card-text">{{v.modelo}}</p>
              <a href="/veiculo/{{v.id}}" class="btn btn-primary">
                <i class="fa fa-edit"></i>
              </a>
              <a href="/veiculo/deletar/{{v.id}}" class="btn btn-danger">
                <i class="fa fa-trash"></i>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </center>
    </div>
  </div>
{% endblock %}

templates/veiculo/novo.html
{% extends "../base.html" %}

{% block titulo %} Cadastro de novos veículos {% endblock %}

{% block conteudo %}

<form action="/veiculo/novo/" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="col-6">
      <label for="marca" class="form-label">Marca</label>
      {{ form.marca }}
    </div>
    <div class="col-6">
    <label for="modelo" class="form-label">Modelo</label>
      {{ form.modelo }}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label for="ano" class="form-label">Ano</label>
      {{ form.ano }}
    </div>
    <div class="col-6">
      <label for="cor" class="form-label">Cor</label>
      {{ form.cor }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <label for="combustivel" class="form-label">Combustível</label>
      {{ form.combustivel }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <label for="foto" class="form-label">Foto</label>
      {{ form.foto }}
    </div>
  </div>
  <input type="submit" value="Salvar" class="btn btn-primary mt-3 float-end" />
</form>

{% endblock %}